"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 08:49:31.251412
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('installed_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugins')),
    sa.UniqueConstraint('name', name=op.f('uq_plugins_name'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lane_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('scale', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_table('timing_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_timing_configurations_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timing_configurations'))
    )
    op.create_table('track_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_layouts_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_layouts'))
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('track_layout_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_laps', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_races_track_id_tracks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_layout_id'], ['track_layouts.id'], name=op.f('fk_races_track_layout_id_track_layouts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races'))
    )
    op.create_table('timing_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['timing_configurations.id'], name=op.f('fk_timing_sensors_configuration_id_timing_configurations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timing_sensors')),
    sa.UniqueConstraint('configuration_id', 'sensor_id', 'lane', name=op.f('uq_timing_sensors_configuration_id_sensor_id_lane'))
    )
    op.create_table('race_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_race_participants_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_participants_race_id_races'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_race_participants_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_participants')),
    sa.UniqueConstraint('race_id', 'driver_id', name=op.f('uq_race_participants_race_id_driver_id')),
    sa.UniqueConstraint('race_id', 'lane', name=op.f('uq_race_participants_race_id_lane'))
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_ns', sa.BigInteger(), nullable=False),
    sa.Column('race_time_ns', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['race_participants.id'], name=op.f('fk_laps_participant_id_race_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_laps_race_id_races'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laps')),
    sa.UniqueConstraint('participant_id', 'lap_number', name=op.f('uq_laps_participant_id_lap_number'))
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.Column('sector_number', sa.Integer(), nullable=False),
    sa.Column('sector_time_ns', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], name=op.f('fk_sectors_lap_id_laps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors')),
    sa.UniqueConstraint('lap_id', 'sector_number', name=op.f('uq_sectors_lap_id_sector_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sectors')
    op.drop_table('laps')
    op.drop_table('race_participants')
    op.drop_table('timing_sensors')
    op.drop_table('races')
    op.drop_table('track_layouts')
    op.drop_table('timing_configurations')
    op.drop_table('vehicles')
    op.drop_table('tracks')
    op.drop_table('settings')
    op.drop_table('plugins')
    op.drop_table('drivers')
    # ### end Alembic commands ###
